### ISSUE TITLE
Server.pro, MC 1.17 - java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by WillyJL** [Imprex-Development/orebfuscator#104]
**Please fill out the following information:**

* Server Version: `CraftBukkit version 3141-Spigot-66f9d3c-72a2901 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`
* Orebfuscator Version: `5.1.4` official / also `5.1.4` from [1.17 dev branch](https://github.com/Imprex-Development/Orebfuscator/tree/96-1.17) ([artifact](https://github.com/Imprex-Development/Orebfuscator/actions/runs/932200425))
* Protocollib Version: `4.7.0-SNAPSHOT-b507` ([updated an hour ago](https://github.com/dmulloy2/ProtocolLib/issues/1209))
* Hosting (in case it matters): `server.pro`, `2GB ram` - `20GB storage` - `2 vCores`

**Describe the bug**

1. Install Orebfuscator and ProtocolLib
2. Run server
3. After spawn area is prepared Orebfuscator tries to load but fails:
```
[23:25:27] [Server thread/INFO]: [Orebfuscator] Enabling Orebfuscator v5.1.4
[23:25:27] [Server thread/ERROR]: [Orebfuscator] An error occurred while enabling plugin
[23:25:27] [Server thread/ERROR]: [Orebfuscator] null
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at java.nio.file.Files.copy(Unknown Source) ~[?:?]
	at net.imprex.orebfuscator.config.OrebfuscatorConfig.createConfigIfNotExist(OrebfuscatorConfig.java:82) ~[?:?]
	at net.imprex.orebfuscator.config.OrebfuscatorConfig.load(OrebfuscatorConfig.java:53) ~[?:?]
	at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:49) ~[?:?]
	at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:46) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at java.lang.Thread.run(Unknown Source) [?:?]
[23:25:27] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.1.4
[23:25:27] [Server thread/ERROR]: Error occurred while disabling Orebfuscator v5.1.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.imprex.orebfuscator.cache.ChunkCache.close()" because "this.chunkCache" is null
	at net.imprex.orebfuscator.Orebfuscator.onDisable(Orebfuscator.java:92) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.imprex.orebfuscator.Orebfuscator.onEnableFailed(Orebfuscator.java:112) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:349) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
4. A `Orebfuscator` folder was created in `plugins/` but no files inside it.

**Comment by Ingrim4** [comment]
Fixed as of b3b448ddbda78bf2fe7e28b67e5407f8e3312c39
