### ISSUE TITLE
Could not load 'plugins/orebfuscator-plugin-5.1.5.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by arch-user-france1** [Imprex-Development/orebfuscator#115]
**Please fill out the following information:**

* Server Version:  Newest 1.17 SpigotMC
* Orebfuscator Version:  5.1.5
* Protocollib Version: 

**Describe the bug**
Reproduce: Ugrade to 1.17 and ObFu 5.1.5

Both can be:
Doesn't work after changing version in plugins folder &
SpigotMC 1.17 doesn't work prob. with Orebfuscator

org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
...
Caused by: java.util.zip.ZipException: zip END header not found
...

or it is the new Java version that is required (BuldTools forced me)

**Comment by Ingrim4** [comment]
Seems like this problem only exists on your end because I've never heard of anything like this happening. Please make sure you correctly downloaded the latest version of OFC: https://github.com/Imprex-Development/Orebfuscator/releases/tag/5.1.5

**Comment by arch-user-france1** [comment]
I had to download it again... Maybe I renamed it - mistake?

Bruh I just downloaded  https://github.com/Imprex-Development/Orebfuscator/releases/tag/5.1.5 with that:
wget  https://github.com/Imprex-Development/Orebfuscator/releases/tag/5.1.5
But that doesn't work because it is just the page to select what to download not the jar file

**Comment by arch-user-france1** [comment]
I still can't enabled it
it is asking me if it is the newest version and it is
It loads the plugin and crashes on start (bukkit names it enabling)

**Comment by debian-user-france1** [comment]
I reproduced

I logged in as Player
I pressed Command block, joined world2, unloaded and then it crashed

Log:
[08:01:56] [Server thread/INFO]: @: Loaded world 'world2'!
[08:02:07] [Server thread/INFO]: @: Loaded world 'world2'!
[08:02:08] [Server thread/INFO]: [Multiverse-Core] World 'world2' was unloaded from Multiverse.
[08:02:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (world2): All chunks are saved
[08:02:16] [Server thread/INFO]: [Multiverse-Core] World 'world2' was unloaded from Bukkit.
[08:02:16] [Server thread/INFO]: @: Unloaded world 'world2'!
[08:02:16] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758) ~[?:?]
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785) ~[?:?]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1280) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[08:02:16] [Server thread/ERROR]: This crash report has been saved to: /home/france1/MinecraftServer/./crash-reports/crash-2021-07-03_08.02.16-server.txt
[08:02:16] [Server thread/INFO]: Stopping server
[08:02:16] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.1.5
[08:02:16] [Server thread/ERROR]: Error occurred while disabling Orebfuscator v5.1.5 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.imprex.orebfuscator.obfuscation.ObfuscatorSystem.close()" because "this.obfuscatorSystem" is null
	at net.imprex.orebfuscator.Orebfuscator.onDisable(Orebfuscator.java:94) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:429) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:894) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:731) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1071) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3162-Spigot-f773da8-b121d3b]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[08:02:16] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.4.8
[08:02:16] [Server thread/INFO]: [DropHeads] Disabling DropHeads v3.6.7
[08:02:16] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.3.0-b846
[08:02:16] [Server thread/INFO]: [Geyser-Spigot] Disabling Geyser-Spigot v1.2.1-SNAPSHOT
[08:02:16] [Server thread/INFO]: [Geyser-Spigot] Shutting down Geyser.
[08:02:16] [Server thread/INFO]: [Geyser-Spigot] Geyser shutdown successfully.
[08:02:16] [Server thread/INFO]: [AutoSaveWorld] Disabling AutoSaveWorld v4.15
[08:02:16] [Server thread/INFO]: AutoSaving
[08:02:16] [Server thread/INFO]: AutoSave Complete
[08:02:20] [Server thread/INFO]: Saving players
[08:02:20] [Server thread/INFO]: Caramello5839 lost connection: Server closed
[08:02:20] [Server thread/INFO]: Caramello5839 left the game
[08:02:21] [Server thread/INFO]: Saving worlds
[08:02:21] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[08:02:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[08:02:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[08:02:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[08:02:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[08:02:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[08:02:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[08:02:24] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[08:02:24] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
>

**Comment by debian-user-france1** [comment]
http://cloud.bubicloud.ch/nextcloud/index.php/s/8e3qtwn69ZtWbTZ

Here the whole log in logs/latest

**Comment by Ingrim4** [comment]
Can you please provide more info like your Java version, server log and a list of other installed plugins?
