### ISSUE TITLE
HeightAccessor failure

### ISSUE THREAD

**Issue by SlimeDog** [Imprex-Development/orebfuscator#122]
**Please fill out the following information:**
Orebfuscator 5.1.5-b18
```
>version
[10:43:32] [Server thread/INFO]: This server is running CraftBukkit version 3219-Spigot-b166a49-8c6d60c (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[10:43:32] [Server thread/INFO]: You are running the latest version
>version Orebfuscator
[10:43:35] [Server thread/INFO]: Orebfuscator version 5.1.5
[10:43:35] [Server thread/INFO]: High-Performance Anti X-Ray
[10:43:35] [Server thread/INFO]: Authors: Ingrim4, NgLoader, lishid, SydMontague, ProgrammerDan and Aleksey-Terzi
>version ProtocolLib
[10:43:50] [Server thread/INFO]: ProtocolLib version 4.7.1-SNAPSHOT-b531
[10:43:50] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[10:43:50] [Server thread/INFO]: Authors: dmulloy2 and comphenix
```

**Describe the bug**

On player connect, player does not "land", and:
```
[10:40:44] [Server thread/WARN]: [Orebfuscator] Task #11746 for Orebfuscator v5.1.5 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class net.imprex.orebfuscator.util.HeightAccessor
        at net.imprex.orebfuscator.obfuscation.Obfuscator.obfuscateNow(Obfuscator.java:50) ~[?:?]
        at net.imprex.orebfuscator.obfuscation.Obfuscator.lambda$obfuscate$0(Obfuscator.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[10:40:44] [Server thread/WARN]: [Orebfuscator] Task #11747 for Orebfuscator v5.1.5 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class net.imprex.orebfuscator.util.HeightAccessor
        at net.imprex.orebfuscator.obfuscation.Obfuscator.obfuscateNow(Obfuscator.java:50) ~[?:?]
        at net.imprex.orebfuscator.obfuscation.Obfuscator.lambda$obfuscate$0(Obfuscator.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1-3219.jar:3219-Spigot-b166a49-8c6d60c]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by SlimeDog** [comment]
confirmed fixed in build 20. Thanks.
