### ISSUE TITLE
Exceptions with 1.17.1

### ISSUE THREAD

**Issue by Bobcat00** [Imprex-Development/orebfuscator#173]
**Please fill out the following information:**

* Server Version: git-Paper-408 (MC: 1.17.1)
* Orebfuscator Version: 5.2.3
* Protocollib Version: 4.7.0

**Describe the bug**

I get multiple of the following exceptions. They appear to happen when teleporting. orebfuscator_cache was cleared before starting the server.
```
2022-01-06 10:12:22 [WARN] java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.ChunkSection.c()" because "section" is null
2022-01-06 10:12:22 [WARN] 	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
2022-01-06 10:12:22 [WARN] 	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
2022-01-06 10:12:22 [WARN] 	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1093)
2022-01-06 10:12:22 [WARN] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
2022-01-06 10:12:22 [WARN] 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
2022-01-06 10:12:22 [WARN] 	at java.base/java.lang.Thread.run(Thread.java:831)
2022-01-06 10:12:22 [WARN] Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.ChunkSection.c()" because "section" is null
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.nms.v1_17_R1.ReadOnlyChunkWrapper.getState(ReadOnlyChunkWrapper.java:22)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.nms.v1_17_R1.ReadOnlyChunkWrapper.getBlockState(ReadOnlyChunkWrapper.java:31)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.obfuscation.ObfuscationTask.getBlockState(ObfuscationTask.java:49)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.isAdjacentBlockOccluding(ObfuscationProcessor.java:135)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.shouldObfuscate(ObfuscationProcessor.java:122)
2022-01-06 10:12:22 [WARN] 	at Orebfuscator.jar//net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:74)
2022-01-06 10:12:22 [WARN] 	... 2 more
```

**Comment by Ingrim4** [comment]
Maybe I should start testing this on older versions of the game (or at least current version and the one before) xD
