### ISSUE TITLE
CompletionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Delta203** [Imprex-Development/orebfuscator#183]
**Please fill out the following information:**

* Server Version: spigot 1.12.2 (final build)
* Orebfuscator Version: orebfuscator-plugin-5.2.4.jar
* Protocollib Version: ProtocolLib.jar 4.7.0

**Describe the bug**
The plugin is working absolutely fine. However, after I join my normal world. My console get spammed like this:
```
[01:45:39] [ofc-task-worker-1/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:45:39] [ofc-task-worker-1/WARN]: Caused by: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.nms.v1_12_R1.ReadOnlyChunkWrapper.getBlockState(ReadOnlyChunkWrapper.java:16)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.getBlockState(ObfuscationTask.java:49)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.isAdjacentBlockOccluding(ObfuscationProcessor.java:135)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.shouldObfuscate(ObfuscationProcessor.java:123)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:74)
[01:45:39] [ofc-task-worker-1/WARN]: 	... 2 more
[01:45:39] [ofc-task-worker-0/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-0/WARN]: 	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
[01:45:39] [ofc-task-worker-0/WARN]: 	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
[01:45:39] [ofc-task-worker-0/WARN]: 	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
[01:45:39] [ofc-task-worker-0/WARN]: 	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
[01:45:39] [ofc-task-worker-0/WARN]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[01:45:39] [ofc-task-worker-0/WARN]: 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
[01:45:39] [ofc-task-worker-0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:45:39] [ofc-task-worker-0/WARN]: Caused by: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.nms.v1_12_R1.ReadOnlyChunkWrapper.getBlockState(ReadOnlyChunkWrapper.java:16)
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.getBlockState(ObfuscationTask.java:49)
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.isAdjacentBlockOccluding(ObfuscationProcessor.java:135)
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.shouldObfuscate(ObfuscationProcessor.java:123)
[01:45:39] [ofc-task-worker-0/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:74)
[01:45:39] [ofc-task-worker-0/WARN]: 	... 2 more
[01:45:39] [ofc-task-worker-5/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-5/WARN]: 	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
[01:45:39] [ofc-task-worker-5/WARN]: 	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
[01:45:39] [ofc-task-worker-5/WARN]: 	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
[01:45:39] [ofc-task-worker-5/WARN]: 	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
[01:45:39] [ofc-task-worker-5/WARN]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[01:45:39] [ofc-task-worker-5/WARN]: 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
[01:45:39] [ofc-task-worker-5/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:45:39] [ofc-task-worker-5/WARN]: Caused by: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.nms.v1_12_R1.ReadOnlyChunkWrapper.getBlockState(ReadOnlyChunkWrapper.java:16)
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.getBlockState(ObfuscationTask.java:49)
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.isAdjacentBlockOccluding(ObfuscationProcessor.java:135)
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.shouldObfuscate(ObfuscationProcessor.java:123)
[01:45:39] [ofc-task-worker-5/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:74)
[01:45:39] [ofc-task-worker-5/WARN]: 	... 2 more
[01:45:39] [ofc-task-worker-4/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-4/WARN]: 	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
[01:45:39] [ofc-task-worker-4/WARN]: 	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
[01:45:39] [ofc-task-worker-4/WARN]: 	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
[01:45:39] [ofc-task-worker-4/WARN]: 	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
[01:45:39] [ofc-task-worker-4/WARN]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[01:45:39] [ofc-task-worker-4/WARN]: 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
[01:45:39] [ofc-task-worker-4/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:45:39] [ofc-task-worker-4/WARN]: Caused by: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.nms.v1_12_R1.ReadOnlyChunkWrapper.getBlockState(ReadOnlyChunkWrapper.java:16)
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.getBlockState(ObfuscationTask.java:49)
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.isAdjacentBlockOccluding(ObfuscationProcessor.java:135)
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.shouldObfuscate(ObfuscationProcessor.java:123)
[01:45:39] [ofc-task-worker-4/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:74)
[01:45:39] [ofc-task-worker-4/WARN]: 	... 2 more
[01:45:39] [ofc-task-worker-2/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-2/WARN]: 	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
[01:45:39] [ofc-task-worker-2/WARN]: 	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
[01:45:39] [ofc-task-worker-2/WARN]: 	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
[01:45:39] [ofc-task-worker-2/WARN]: 	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
[01:45:39] [ofc-task-worker-2/WARN]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[01:45:39] [ofc-task-worker-2/WARN]: 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
[01:45:39] [ofc-task-worker-2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:45:39] [ofc-task-worker-2/WARN]: Caused by: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.nms.v1_12_R1.ReadOnlyChunkWrapper.getBlockState(ReadOnlyChunkWrapper.java:16)
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.getBlockState(ObfuscationTask.java:49)
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.isAdjacentBlockOccluding(ObfuscationProcessor.java:135)
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.shouldObfuscate(ObfuscationProcessor.java:123)
[01:45:39] [ofc-task-worker-2/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:74)
[01:45:39] [ofc-task-worker-2/WARN]: 	... 2 more
[01:45:39] [ofc-task-worker-1/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:45:39] [ofc-task-worker-1/WARN]: Caused by: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-3/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-3/WARN]: 	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
[01:45:39] [ofc-task-worker-3/WARN]: 	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
[01:45:39] [ofc-task-worker-3/WARN]: 	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
[01:45:39] [ofc-task-worker-3/WARN]: 	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
[01:45:39] [ofc-task-worker-3/WARN]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[01:45:39] [ofc-task-worker-3/WARN]: 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
[01:45:39] [ofc-task-worker-3/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
[01:45:39] [ofc-task-worker-3/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
[01:45:39] [ofc-task-worker-3/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
[01:45:39] [ofc-task-worker-3/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
[01:45:39] [ofc-task-worker-3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:45:39] [ofc-task-worker-3/WARN]: Caused by: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-1/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationRequest.completeExceptionally(ObfuscationRequest.java:73)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTask.completeExceptionally(ObfuscationTask.java:44)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationProcessor.process(ObfuscationProcessor.java:103)
[01:45:39] [ofc-task-worker-1/WARN]: 	at net.imprex.orebfuscator.obfuscation.ObfuscationTaskWorker.run(ObfuscationTaskWorker.java:39)
[01:45:39] [ofc-task-worker-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
...

This are actually two different errors but they are both java.lang.NullPointerException. You should copy my cutout into a texteditor to have a clear look of the error.

Hope you can fix it. The plugin is working totally fine but this console errors are really annoying.
Thank you!

**Comment by Ingrim4** [comment]
Will be fixed in the next update till then here's a pre-release version with the fix applied: https://github.com/Imprex-Development/Orebfuscator/suites/5076431459/artifacts/151155150

**Comment by Delta203** [comment]
Nice thank you!
