### ISSUE TITLE
Plugin Doesn't Start

### ISSUE THREAD

**Issue by xEchoes** [Imprex-Development/orebfuscator#205]
### Description

Doesn't start after it was downloaded. Error message here:

[00:14:54 ERROR]: Error occurred while disabling Orebfuscator v5.2.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.imprex.orebfuscator.cache.ObfuscationCache.close()" because "this.obfuscationCache" is null
        at net.imprex.orebfuscator.Orebfuscator.onDisable(Orebfuscator.java:95) ~[orebfuscator-plugin-5.2.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.imprex.orebfuscator.Orebfuscator.onEnableFailed(Orebfuscator.java:115) ~[orebfuscator-plugin-5.2.6.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-132]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:381) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Reproduction Steps

Doesn't start after downloading. I do have protocollib.

### Expected Behaviour

It should be enabled

### Server Details

Not Enabled, Paper 1.18.0

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

**Comment by Ingrim4** [comment]
Can you please provider your full log as the error you provided isn't the first one but only the by-product of another previous exception.

**Comment by xEchoes** [comment]
yup

[14:08:40 INFO]: [Orebfuscator] Enabling Orebfuscator v5.2.6
[14:08:40 WARN]: [bukkit.orebfuscator] [Orebfuscator] config section 'advanced' is missing, using default one
[14:08:40 ERROR]: [bukkit.orebfuscator] [Orebfuscator] An error occurred while enabling plugin
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because "obfuscation" is null
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.deserialize(OrebfuscatorConfig.java:143) ~[orebfuscator-plugin-5.2.6.jar:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.load(OrebfuscatorConfig.java:58) ~[orebfuscator-plugin-5.2.6.jar:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:52) ~[orebfuscator-plugin-5.2.6.jar:?]
        at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:47) ~[orebfuscator-plugin-5.2.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:08:40 INFO]: [Orebfuscator] Disabling Orebfuscator v5.2.6
[14:08:40 ERROR]: Error occurred while disabling Orebfuscator v5.2.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.imprex.orebfuscator.cache.ObfuscationCache.close()" because "this.obfuscationCache" is null
        at net.imprex.orebfuscator.Orebfuscator.onDisable(Orebfuscator.java:95) ~[orebfuscator-plugin-5.2.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.imprex.orebfuscator.Orebfuscator.onEnableFailed(Orebfuscator.java:115) ~[orebfuscator-plugin-5.2.6.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-132]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:381) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Ingrim4** [comment]
It appears as if your config is wrongly formatted or configured, please delete your config so Orebfuscator can regenerate the default one.

**Comment by xEchoes** [comment]
works, thanks
