### ISSUE TITLE
Plugin Orebfuscator not working

### ISSUE THREAD

**Issue by Lisojelen** [Imprex-Development/orebfuscator#216]
### Description

so after dowloading on the server protocol Lib, and Orebfuscator, and restarting server the plugin does not work. Did not even create it's folder in plugins folder

### Reproduction Steps

Install the plugins ProtocolLib, and Orebfuscator on a paper-1.18.1-216 server.

### Expected Behaviour

working as normal

### Server Details

paper-1.18.1-216

### Orebfuscator Version

5.2.6

### ProtocolLib Version

4.8.0

### Logs and Configs

https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/
https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Lisojelen** [comment]
so now something happend, and after like 5th restart plugin created it's folder, but still does not work

**Comment by NgLoader** [comment]
Can you please share us the console output?

**Comment by IamN4m3l3ss** [comment]
Console output:

<html>
<body>


[15:02:36] [Server thread/ERROR]: Could not load 'plugins/orebfuscator-plugin-5.2.6.jar' in folder 'plugins'
--
15 | org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'Orebfuscator'.
16 | at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
17 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-312]
18 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-312]
19 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-312]
20 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-312]
21 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
22 | [15:02:36] [Server thread/ERROR]: Could not load 'plugins/AntiCheatReloaded.jar' in folder 'plugins'
23 | org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'AntiCheatReloaded'.
24 | at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
25 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-312]
26 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-312]
27 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-312]
28 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-312]
29 | at java.lang.Thread.run(Thread.java:833) ~[?:?]


</body>
</html>[15:02:36] [Server thread/ERROR]: Could not load 'plugins/orebfuscator-plugin-5.2.6.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'Orebfuscator'.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:3[15](https://exaroton.com/log/#L15)) ~[paper-1.18.2.jar:git-Paper-312]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:02:36] [Server thread/ERROR]: Could not load 'plugins/AntiCheatReloaded.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'AntiCheatReloaded'.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1[16](https://exaroton.com/log/#L16)3) ~[paper-1.[18](https://exaroton.com/log/#L18).2.jar:git-Paper-312]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-312]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NgLoader** [comment]
You don't have installed ProtocolLib. 

**[Server thread/ERROR]: Could not load 'plugins/orebfuscator-plugin-5.2.6.jar' in folder 'plugins' org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'Orebfuscator'.**
