### ISSUE TITLE
Chunks are not loaded

### ISSUE THREAD

**Issue by dol4iua** [Imprex-Development/orebfuscator#246]
### Description

[04:57:51] [ofc-chunk-serializer/WARN]: java.io.IOException: Unable to read chunk: [CraftWorld{name=world}, -2, 604]
[04:57:51] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:54)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer$ReadTask.run(AsyncChunkSerializer.java:166)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer.run(AsyncChunkSerializer.java:107)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:57:51] [ofc-chunk-serializer/WARN]: Caused by: java.util.zip.ZipException: invalid code lengths set
[04:57:51] [ofc-chunk-serializer/WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at net.minecraft.util.FastBufferedInputStream.b(FastBufferedInputStream.java:94)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at net.minecraft.util.FastBufferedInputStream.read(FastBufferedInputStream.java:42)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:37)
[04:57:51] [ofc-chunk-serializer/WARN]: 	... 3 more
[04:57:52] [ofc-chunk-serializer/WARN]: java.io.IOException: Unable to read chunk: [CraftWorld{name=world}, -5, 605]
[04:57:52] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:54)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer$ReadTask.run(AsyncChunkSerializer.java:166)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer.run(AsyncChunkSerializer.java:107)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:57:52] [ofc-chunk-serializer/WARN]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at net.minecraft.util.FastBufferedInputStream.b(FastBufferedInputStream.java:94)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at net.minecraft.util.FastBufferedInputStream.read(FastBufferedInputStream.java:42)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:37)
[04:57:52] [ofc-chunk-serializer/WARN]: 	... 3 more

### Reproduction Steps

I don't know how it appeared

### Expected Behaviour

Chunks are not loaded

### Server Details

purpur-1.19.2-1777.jar

### Orebfuscator Version

orebfuscator-plugin-5.3.0.jar

### ProtocolLib Version

5.0.0 snapshot b569

### Logs and Configs

[04:57:51] [ofc-chunk-serializer/WARN]: java.io.IOException: Unable to read chunk: [CraftWorld{name=world}, -2, 604]
[04:57:51] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:54)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer$ReadTask.run(AsyncChunkSerializer.java:166)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer.run(AsyncChunkSerializer.java:107)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:57:51] [ofc-chunk-serializer/WARN]: Caused by: java.util.zip.ZipException: invalid code lengths set
[04:57:51] [ofc-chunk-serializer/WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at net.minecraft.util.FastBufferedInputStream.b(FastBufferedInputStream.java:94)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at net.minecraft.util.FastBufferedInputStream.read(FastBufferedInputStream.java:42)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
[04:57:51] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:37)
[04:57:51] [ofc-chunk-serializer/WARN]: 	... 3 more
[04:57:52] [ofc-chunk-serializer/WARN]: java.io.IOException: Unable to read chunk: [CraftWorld{name=world}, -5, 605]
[04:57:52] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:54)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer$ReadTask.run(AsyncChunkSerializer.java:166)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer.run(AsyncChunkSerializer.java:107)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:57:52] [ofc-chunk-serializer/WARN]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at net.minecraft.util.FastBufferedInputStream.b(FastBufferedInputStream.java:94)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at net.minecraft.util.FastBufferedInputStream.read(FastBufferedInputStream.java:42)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
[04:57:52] [ofc-chunk-serializer/WARN]: 	at orebfuscator-plugin-5.3.0.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:37)
[04:57:52] [ofc-chunk-serializer/WARN]: 	... 3 more

### Extra Details

https://www.youtube.com/watch?v=U1r4hch8rrA

**Comment by dol4iua** [comment]
ProtocolLib Dump
Timestamp: 10/26/22 13:13:10

ProtocolLib Version: ProtocolLib v5.0.0-SNAPSHOT-b569
Bukkit Version: 1.19.2-R0.1-SNAPSHOT
Server Version: git-Purpur-1777 (MC: 1.19.2)
Java Version: 17.0.4

ProtocolLib: com.comphenix.protocol.ProtocolLib@681596f1[
  statistics=com.comphenix.protocol.metrics.Statistics@675cf5fc
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@5ce95f2f
  packetTask=8
  tickCounter=4586599
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@7effb05b
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@3a99136b
  commandProtocol=com.comphenix.protocol.CommandProtocol@3aeaf2d1
  commandPacket=com.comphenix.protocol.CommandPacket@2cecd284
  commandFilter=com.comphenix.protocol.CommandFilter@2f92d22a
  packetLogging=com.comphenix.protocol.PacketLogging@5d628ef8
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@30f383ff
  server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1777,minecraftVersion=1.19.2}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@437b9177
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v5.0.0-SNAPSHOT-b569, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@26e7546e
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@54284a82[
  plugin=ProtocolLib v5.0.0-SNAPSHOT-b569
  server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1777,minecraftVersion=1.19.2}
  reporter=com.comphenix.protocol.ProtocolLib$1@4b479959
  minecraftVersion=(MC: 1.19.2)
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7f41002d
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@63197f8f
  inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@75734534
  outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2098792
  registeredListeners=[PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[PONG[class=ServerboundPongPacket, id=31]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=30], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=17]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=30], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[GROUND[class=d, id=22], POSITION[class=PacketPlayInPosition, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=20], LOOK[class=PacketPlayInLook, id=21]], gamephase=PLAYING, options=[]]], com.comphenix.protocol.async.NullPacketListener@19dbe6e0, PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[GROUND[class=d, id=22], POSITION[class=PacketPlayInPosition, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=20], LOOK[class=PacketPlayInLook, id=21]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=25]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@75beaf96
  playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@5d7353a9
  networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@3246f7d6
  debug=false
  closed=false
  injected=true
]

Listeners:
com.gmail.olexorus.themis.y8@271e8aba[
  plugin=Themis v0.13.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[PONG[class=ServerboundPongPacket, id=31]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.gmail.olexorus.themis.L5@772b771e[
  plugin=Themis v0.13.0
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=30], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=17]], gamephase=PLAYING, options=[]]
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=30], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=17]], gamephase=PLAYING, options=[]]
]
com.gmail.olexorus.themis.ym@48c40881[
  o=com.gmail.olexorus.themis.HU@28ef2139
  plugin=Themis v0.13.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=27]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.gmail.olexorus.themis.HM@278d5184[
  P=com.gmail.olexorus.themis.HU@28ef2139
  plugin=Themis v0.13.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[GROUND[class=d, id=22], POSITION[class=PacketPlayInPosition, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=20], LOOK[class=PacketPlayInLook, id=21]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.comphenix.protocol.async.NullPacketListener@19dbe6e0[
  sendingWhitelist=ListeningWhitelist[priority=LOW, packets=[MAP_CHUNK[class=ClientboundLevelChunkWithLightPacket, id=31]], gamephase=PLAYING, options=[ASYNC]]
  receivingWhitelist=ListeningWhitelist[priority=LOW, packets=[], gamephase=PLAYING, options=[ASYNC]]
  plugin=Orebfuscator v5.3.0
]
com.gmail.olexorus.themis.am@536a8104[
  plugin=Themis v0.13.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=LOW, packets=[GROUND[class=d, id=22], POSITION[class=PacketPlayInPosition, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=20], LOOK[class=PacketPlayInLook, id=21]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.gmail.olexorus.themis.yb@2ce93aa7[
  p=com.gmail.olexorus.themis.HU@28ef2139
  plugin=Themis v0.13.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=25]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
Orebfuscator by [Ingrim4, NgLoader, lishid, SydMontague, ProgrammerDan, Aleksey-Terzi]
Themis by [Olexorus]

**Comment by dol4iua** [comment]
I regen the chunk, it didn't help

**Comment by dol4iua** [comment]
I //set 0 these chunks, the problem did not disappear

**Comment by dol4iua** [comment]
I fix it , remove orebfuscator_cache for this chunks!!

**Comment by dol4iua** [comment]
BTW TY FOR HELP)

**Comment by NgLoader** [comment]
Sry, for the late response.
It seems that your world has set a not valid chunk value, did you edited it worldedit or any other plugin/mod?

**Comment by dol4iua** [comment]
No, this 
it happened by itself after restarting the server. there were no buildings in the tanks, they were like after generation.

**Comment by Ingrim4** [comment]
Yeah this was caused by an corrupted cache file (`Caused by: java.io.EOFException: Unexpected end of ZLIB input stream`). Since we are using minecrafts internal region file code I can't really tell you what happened in your case but I would guess the server shutdown unexpectedly and couldn't finish writing the cache file. Simply clear the cache should a similar error ever appear if that doesn't help feel free to create a new issue here.
