### ISSUE TITLE
The Plugin

### ISSUE THREAD

**Issue by NicDevTV** [Imprex-Development/orebfuscator#305]
### Description

[12:37:18 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/orebfuscator-plugin-5.4.0 2.jar' in 'p lugins'
org.bukkit.plugin. UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please downlo ad and install these plugins to run 'Orebfuscator'.
at io.papermc.paper.plugin.entrypoint. strategy. modern. ModernPluginLoadingStrategy. loadProviders (Modern
PluginLoadingStrategy.java:82) ~[paper-1.20.1. jar: git-Paper-65]
at io.papermc.paper.plugin.storage. SimpleProviderStorage.enter ( SimpleProviderStorage. java:39) ~[paper-
1.20.1.jar:git-Paper-65]
at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[paper-1.20.1.jar:git-Paper-65]
at org.bukkit.craftbukkit. V1_20_R1.CraftServer. loadPlugins (CraftServer. java: 507) ~[paper-1.20.1.jar:gi
t-Paper-65]
at net.minecraft.server. dedicated. DedicatedServer.initServer (DedicatedServer. java:273) ~[paper 1.20.1.
jar:git-Paper-65]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101)~[paper-1.20.1.jar:git-Pa
per-65]
at net.minecraft.server.MinecraftServer. lambda$spin$0 (MinecraftServer. java: 318) ~[paper-1.20.1.jar:git
-Paper-65]
at java.land.Thread.run(Thread java:833) ~[?:?1

### Reproduction Steps

I just installed Protocolib and Orbfuscat.

### Expected Behaviour

There is an error.

### Orebfuscator Dump

It doesn't work

**Comment by Ingrim4** [comment]
It's in the error you posted: `Unknown/missing dependency plugins: [ProtocolLib]. Please downlonad and install these plugins to run 'Orebfuscator'.`, your missing ProtocolLib
