### ISSUE TITLE
how use new versions plugin on 1.12.2 if 1.12.2 dont support jdk 17? the server is crashing

### ISSUE THREAD

**Issue by SL-69** [Imprex-Development/orebfuscator#309]
### Description

how use new versions plugin on 1.12.2 if 1.12.2 dont support jdk 17? the server is crashing

### Reproduction Steps

download plugin, and depended jdk 17 for plugin. start server on paper 1.12.2

### Expected Behaviour

work plugin

### Orebfuscator Dump

https://gist.github.com/ICodeMonster/18e94a6f0423b0038e31e028d0009e88

### Extra Details
Without jdk 17:
[14:05:46 ERROR]: Could not load 'plugins\orebfuscator-plugin-5.4.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more

With jdk 17 other plugins and server crash

**Comment by Ingrim4** [comment]
I don't think Orebfuscator will support any Java version before 17 in future updates since Mojang/Microsoft kinda forced us to update to Java 17 since they are now using record classes. On another note Paper 1.12.2 and ProtocolLib both support Java 17 without any issues. So why don't you simply upgrade to Java 17?

**Comment by SL-69** [comment]
if i upgrade to java 17 - server crash

**Comment by Ingrim4** [comment]
Then I would recommend to move to a newer Minecraft version or to update all the other plugins on your server cause they are at fault if you server crashes on Java 17.

**Comment by SL-69** [comment]
Can you make separate support for versions below 1.13? I could upgrade to a newer version, but few versions work well in my country due to the abundance of low end computers.

**Comment by Ingrim4** [comment]
I'm sorry to say this but Minecraft 1.12.2 is almost 6 years old and I don't have the time or resources to support each combination of java, game version and plugin. Especially if only [18 servers (0.6%)](https://bstats.org/plugin/bukkit/Orebfuscator/8942) are using the version. **You can still use older version of Orebfuscator** or create a fork and downgrade it yourself to Java 8, since Orebfuscator is FOSS.

**Comment by SL-69** [comment]
okay, thank u
