### ISSUE TITLE
Incompatible with 1.16.2

### ISSUE THREAD

**Issue by schrodingerneko** [Imprex-Development/orebfuscator#31]
**Please fill out the following information:**
* Server Version: 1.16.2
* Orebfuscator Version: Release v5.0.0-v16-pre
* Protocollib Version: ProtocolLib 4.5.1

**Describe the bug**
Describe the bug clearly and how to produce it

Incompatible with 1.16.2

**Comment by NgLoader** [comment]
Can you please describe what's wrong and not only inkompatibel please?

**Comment by schrodingerneko** [comment]
> inkompatibel뿐만 아니라 무엇이 잘못되었는지 설명해 주시겠습니까?

console log

[18:26:02] [Server thread/INFO]: [Orebfuscator] Enabling Orebfuscator v5.0.1
[18:26:02] [Server thread/INFO]: [OFC] Searching NMS protocol for server version "v1_16_R2"!
[18:26:02] [Server thread/ERROR]: [OFC] java.lang.RuntimeException: Server version "v1_16_R2" is currently not supported!
[18:26:02] [Server thread/WARN]: java.lang.RuntimeException: Server version "v1_16_R2" is currently not supported!
[18:26:02] [Server thread/WARN]: 	at net.imprex.orebfuscator.NmsInstance.initialize(NmsInstance.java:83)
[18:26:02] [Server thread/WARN]: 	at net.imprex.orebfuscator.config.OrebfuscatorConfig.serialize(OrebfuscatorConfig.java:121)
[18:26:02] [Server thread/WARN]: 	at net.imprex.orebfuscator.config.OrebfuscatorConfig.reload(OrebfuscatorConfig.java:55)
[18:26:02] [Server thread/WARN]: 	at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:48)
[18:26:02] [Server thread/WARN]: 	at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:43)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.reload(CraftServer.java:874)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:642)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[18:26:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
[18:26:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[18:26:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:26:02] [Server thread/ERROR]: An error occurred by enabling plugin
[18:26:02] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.0.1
[18:26:02] [Server thread/ERROR]: Error occurred while disabling Orebfuscator v5.0.1 (Is it up to date?)
java.lang.NullPointerException: null
	at net.imprex.orebfuscator.Orebfuscator.onDisable(Orebfuscator.java:75) ~[orebfuscator-plugin-v5.0.0-v16-pre.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.imprex.orebfuscator.Orebfuscator.onEnableFailed(Orebfuscator.java:95) ~[orebfuscator-plugin-v5.0.0-v16-pre.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:358) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.reload(CraftServer.java:874) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.Bukkit.reload(Bukkit.java:642) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by NgLoader** [comment]
Thanks, the 1.16.2 is currently not supported but I will push a supported version today.

**Comment by schrodingerneko** [comment]
> 감사합니다. 1.16.2는 현재 지원되지 않지만 오늘 지원되는 버전을 푸시하겠습니다.

Thank you very much for your quick reply.

**Comment by NgLoader** [comment]
Part of 5.0.0 release

**Comment by NgLoader** [comment]
5.0.0 is now released [Download](https://github.com/Imprex-Development/Orebfuscator/releases/tag/5.0.0)
