### ISSUE TITLE
Stuck on Loading Terrain 

### ISSUE THREAD

**Issue by juliohaga** [Imprex-Development/orebfuscator#318]
### Description

Hi! :)
When i log in i get stuck on loading terrain screen, can u help with this?
(If i turn off the plugin, i don't got stuck)

### Reproduction Steps

(Sorry, I'm not a really git hub expert)

The only other plugin I use that can be related to orebfuscator is Chunky, (which loads chunks haha)

### Expected Behaviour

I'm not sure what I need to answer here, but I expected I don't get stuck in loading terrain haha

### Orebfuscator Dump

Sorry, I couldn't use the dump command
It showed this error:

org.bukkit.command.CommandException: Unhandled exception executing command 'orebfuscator' in plugin Orebfuscator v5.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:874) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1922) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:840) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:339) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:517) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:472) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.imprex.orebfuscator.OrebfuscatorCommand.onCommand(OrebfuscatorCommand.java:103) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more

### Extra Details

Sorry if I wasn't clear, my english is kinda bad :p

**Comment by Ingrim4** [comment]
Can you please provide your whole log file since it looks like Orebfuscator didn't initialize successfully. (You can upload your log here: https://gist.github.com/)

**Comment by Ingrim4** [comment]
Closed due to inactivity.
