### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by ErikBS-77** [Imprex-Development/orebfuscator#323]
### Description

[19:37:34 ERROR]: Could not load 'plugins\orebfuscator-plugin-5.4.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_381]
Caused by: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_381]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_381]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_381]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        ... 6 more

### Reproduction Steps

[19:37:34 ERROR]: Could not load 'plugins\orebfuscator-plugin-5.4.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_381]
Caused by: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_381]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_381]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_381]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        ... 6 more

### Expected Behaviour

[19:37:34 ERROR]: Could not load 'plugins\orebfuscator-plugin-5.4.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_381]
Caused by: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_381]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_381]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_381]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        ... 6 more

### Orebfuscator Dump

[19:37:34 ERROR]: Could not load 'plugins\orebfuscator-plugin-5.4.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_381]
Caused by: java.lang.UnsupportedClassVersionError: net/imprex/orebfuscator/Orebfuscator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_381]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_381]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_381]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        ... 6 more

### Extra Details

When i start server this error shows up

**Comment by Ingrim4** [comment]
You're using Java 8 which is no longer supported the build you're using needs Java 17+ or higher and the [latest build](https://github.com/Imprex-Development/orebfuscator/suites/16222674163/artifacts/926640930) needs Java 11+. So you have to update your Java and might need to use the latest master build until the next release.
