### ISSUE TITLE
1.20.1 plugin does not work.

### ISSUE THREAD

**Issue by mlbhc** [Imprex-Development/orebfuscator#335]
### Description

mohist-1.20.1
Orebfuscator v5.4.2
ProtocolLib v5.1.0

### Reproduction Steps

start server

### Expected Behaviour

Get the plugin to work

### Orebfuscator Dump

[dump-2023-11-24_09.30.16.txt](https://github.com/Imprex-Development/orebfuscator/files/13454332/dump-2023-11-24_09.30.16.txt)

### Extra Details

[09:13:29 INFO]: [Orebfuscator] Enabling Orebfuscator v5.4.2
[09:13:29 ERROR]: Error occurred while enabling Orebfuscator v5.4.2 (Is it up to date?)
java.lang.NoSuchFieldError: AIR
        at net.imprex.orebfuscator.nms.v1_20_R1_mojang.NmsManager.<clinit>(NmsManager.java:45) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at com.mohistmc.bukkit.remapping.ReflectionHandler_10.redirectClassForName(ReflectionHandler.java:227) ~[forge-1.20.1-47.2.6-univers
al.jar%23303!/:?]
        at com.mohistmc.bukkit.remapping.ReflectionHandler_10.redirectClassForName(ReflectionHandler.java:220) ~[forge-1.20.1-47.2.6-univers
al.jar%23303!/:?]
        at net.imprex.orebfuscator.OrebfuscatorNms.initialize(OrebfuscatorNms.java:37) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.deserialize(OrebfuscatorConfig.java:137) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.load(OrebfuscatorConfig.java:60) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:54) ~[?:?]
        at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:52) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.6-universal.jar%23303!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.6-universal.jar%23303!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.6-universal.jar%23303!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:548) ~[forge-1.20.1-47.2.6-universal.jar%23303!/:997de3
1d-ddc9a2dad-d2eba2c8-47.2.6]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.2.6-universal.jar%23303!/:997de
31d-ddc9a2dad-d2eba2c8-47.2.6]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:
?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]
[09:13:29 INFO]: [Orebfuscator] Disabling Orebfuscator v5.4.2

**Comment by Ingrim4** [comment]
Can you please check if the latest dev version fixes the issue: https://github.com/Imprex-Development/orebfuscator/suites/17634743365/artifacts/1008308267

**Comment by mlbhc** [comment]
Fixed
