### ISSUE TITLE
Folia doesn't work

### ISSUE THREAD

**Issue by itsjustnickdev** [Imprex-Development/orebfuscator#346]
### Description

Hello,

How did you get it to work on folia as protocolib isn't available on folia?

### Reproduction Steps

install protocolib(doesnt work)
install orebfuscator(errors)

### Expected Behaviour

working

### Orebfuscator Dump

[21:23:39 ERROR]: [Orebfuscator] An error occurred while enabling plugin
java.lang.RuntimeException: ProtocolLib can't be found or is disabled! Orebfuscator can't be enabled.
	at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:48) ~[orebfuscator-plugin-5.4.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by NgLoader** [comment]
You need to use the latest dev build from ProtocolLib

**Comment by itsjustnickdev** [comment]
Can you send me a url to it?

**Comment by itsjustnickdev** [comment]
got it thanks
