### ISSUE TITLE
Oreobfuscator doesnt work

### ISSUE THREAD

**Issue by OnlyTegra** [Imprex-Development/orebfuscator#360]
### Description

Here is the log:
[15:09:05] [Server thread/ERROR]: Error occurred while enabling Orebfuscator v5.4.3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:532) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3871-Bukkit-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3871-Bukkit-3f9263b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:580) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3871-Bukkit-3f9263b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:405) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3871-Bukkit-3f9263b]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:237) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3871-Bukkit-3f9263b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:951) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3871-Bukkit-3f9263b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:295) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3871-Bukkit-3f9263b]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 12 more
[15:09:05] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:09:05] [Server thread/INFO]: Done (13.988s)! For help, type "help"

then it does 

[15:09:06] [Server thread/INFO]: Error Cannot perform automatic updates. (java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null) occurred in ProtocolLib v5.1.0.
[15:09:06] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null
  	at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:540)
  	at com.comphenix.protocol.ProtocolLib.lambda$createPacketTask$0(ProtocolLib.java:511)
  	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:77)
  	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414)
  	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1208)
  	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:374)
  	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1155)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:980)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:295)
  	at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@513937cb[
        plugin=ProtocolLib v5.1.0
        server=CraftServer{serverName=CraftBukkit,serverVersion=3871-Bukkit-3f9263b,minecraftVersion=1.20.1}
        reporter=com.comphenix.protocol.ProtocolLib$1@c5f8d23
        minecraftVersion=(MC: 1.20.1)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@336a5126
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2bf5bfef
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7ea1b681
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@ee71ae3
        registeredListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@6f659978
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@69e959bc
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@1a8fefbe
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@6f642cbe[
      statistics=com.comphenix.protocol.metrics.Statistics@4ce3ac57
      packetTask=com.comphenix.protocol.scheduler.DefaultTask@29f4486a
      tickCounter=20
      configExpectedMod=1
      updater=<null>
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@4bef1ae4
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@520cefb
      commandProtocol=com.comphenix.protocol.CommandProtocol@54f04b1c
      commandPacket=com.comphenix.protocol.CommandPacket@5f4cfef0
      commandFilter=com.comphenix.protocol.CommandFilter@6c47e7c7
      packetLogging=com.comphenix.protocol.PacketLogging@6f93bba2
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@396db5e7
      server=CraftServer{serverName=CraftBukkit,serverVersion=3871-Bukkit-3f9263b,minecraftVersion=1.20.1}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@16e7744
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@f7f21e1
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@20782e20
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.3
  Server:
    3871-Bukkit-3f9263b (MC: 1.20.1)

### Reproduction Steps

I dont know how to reproduce it

### Expected Behaviour

.

### Orebfuscator Dump

https://gist.github.com/RealTegra/5d3b12e5c79a309e2db768101defe970

**Comment by OnlyTegra** [comment]
forgot to say i'm using craftbukkit 1.20.1

**Comment by Ingrim4** [comment]
We don't support plain craftbukkit only spigot and forks of spigot. Please migrate to spigot or paper if possible.
