### ISSUE TITLE
Plugin does not work.

### ISSUE THREAD

**Issue by ghost** [Imprex-Development/orebfuscator#362]
### Description

i am using ProtocolLib v5.1.0. and paper mc version:  This server is running Paper version git-Paper-447 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 0052e2d)

### Reproduction Steps

i started my server and got the following error:

[21:25:15 ERROR]: [Orebfuscator] An error occurred while enabling plugin
java.lang.RuntimeException: ProtocolLib can't be found or is disabled! Orebfuscator can't be enabled.
        at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:48) ~[orebfuscator-plugin-5.4.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-447]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-447]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-447]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-447]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-447]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-447]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-447]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-447]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-447]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
        
        

### Expected Behaviour

the plugin working/ starting...

### Orebfuscator Dump

https://gist.github.com/lean-cc/30e1e360f9029128ee5e3edefb626039
https://gist.github.com/lean-cc/3f9d24826a481e1725adb11fc951b6bc

**Comment by NgLoader** [comment]
You need to install the latest dev build from [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/).
Your current ProtocolLib version only supports up to 1.19
