### ISSUE TITLE
Not working on 1.20.6 spigot

### ISSUE THREAD

**Issue by NoNameiqz** [Imprex-Development/orebfuscator#371]
### Description

It doesnt work on 1.20.6, does anyone have a fix for that?

### Reproduction Steps

Run Spigot 1.20.6

### Expected Behaviour

[Orebfuscator] An error occurred while enabling plugin
java.lang.RuntimeException: Server version "v1_20_R4" is currently not supported!
        at net.imprex.orebfuscator.OrebfuscatorNms.initialize(OrebfuscatorNms.java:41) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.deserialize(OrebfuscatorConfig.java:137) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.load(OrebfuscatorConfig.java:60) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:54) ~[?:?]
        at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:52) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:542) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4165-Spigot-e2c1eee-4af0f22]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:456) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4165-Spigot-e2c1eee-4af0f22]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4165-Spigot-e2c1eee-4af0f22]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4165-Spigot-e2c1eee-4af0f22]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4165-Spigot-e2c1eee-4af0f22]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4165-Spigot-e2c1eee-4af0f22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4165-Spigot-e2c1eee-4af0f22]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: net.imprex.orebfuscator.nms.v1_20_R4.NmsManager
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
        at net.imprex.orebfuscator.OrebfuscatorNms.initialize(OrebfuscatorNms.java:37) ~[?:?]
        ... 15 more
[16:42:43] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.4.3

### Orebfuscator Dump

.

**Comment by NoNameiqz** [comment]
fixed
