### ISSUE TITLE
Problem with ProtocolLib

### ISSUE THREAD

**Issue by KeksNino** [Imprex-Development/orebfuscator#373]
### Description

The plugin would work but Protocollib doesnt load. I have the newest version 5.2.0. But that version only supports to 1.20.4. Am i doing something wrong? Because on spigotmc orebfuscator it says it supports 1.20.6

### Reproduction Steps

.

### Expected Behaviour

.

### Orebfuscator Dump

 [Server thread/WARN]: Unexpected exception while parsing console command "protocol dump"
org.bukkit.command.CommandException: Cannot execute command 'protocol' in plugin ProtocolLib v5.1.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.dispatchCommand(CraftServer.java:887) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.dispatchServerCommand(CraftServer.java:872) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
        at net.minecraft.server.dedicated.DedicatedServer.bq(DedicatedServer.java:427) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:403) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4149-Spigot-e2c1eee-4e7d749]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by NgLoader** [comment]
Can you please try the lastest [ProtocolLib version](https://ci.dmulloy2.net/job/ProtocolLib/689/)?
