### ISSUE TITLE
server crashes on join 

### ISSUE THREAD

**Issue by Endernik** [Imprex-Development/orebfuscator#374]
### Description

on player join server does crash

### Reproduction Steps

everything works well without orebfuscator plugin, i've tried to update protocol and orebfuscator (5.4.4) and nothing did change 

### Expected Behaviour

on player join server does crash, everything works well without orebfuscator plugin, i've tried to update protocol and orebfuscator and nothing did change server version is 1.20.1

### Orebfuscator Dump

https://gist.github.com/Endernik/4b78bd32a0440a150fb5d89619c8e903
https://gist.github.com/Endernik/8f05ec3f3069a48381886b5b5fbb2836

### Extra Details

[09:50:52 ERROR]: Error executing task on Server
net.minecraft.ReportedException: Sending packet
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2318) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2296) ~[?:?]
        at net.minecraft.commands.Commands.runSync(Commands.java:479) ~[?:?]
        at net.minecraft.commands.Commands.lambda$sendAsync$5(Commands.java:460) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1412) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:169) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:563) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:466) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (8).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2310) ~[?:?]
        ... 16 more
[09:50:52 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Sending packet
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1604) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:169) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:563) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:466) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (8).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2310) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2296) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.trackChunk(ServerPlayer.java:2441) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.playerLoadedChunk(ChunkTracker.java:1405) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.updateChunkTracking(ChunkTracker.java:870) ~[?:?]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendChunk(RegionizedPlayerChunkLoader.java:484) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:867) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:244) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:501) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:848) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[purpur-1.20.1.jar:git-Purpur-2062]
        ... 5 more
[09:50:52 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:169) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:563) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:466) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (8).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2310) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2296) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.trackChunk(ServerPlayer.java:2441) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.playerLoadedChunk(ChunkTracker.java:1405) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.updateChunkTracking(ChunkTracker.java:870) ~[?:?]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendChunk(RegionizedPlayerChunkLoader.java:484) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:867) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:244) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:501) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:848) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[09:50:52 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2024-06-02_09.50.52-server.txt
[09:50:52 INFO]: Stopping server

CRASHLOGS:
https://pastebin.com/raw/hN7QbJ6p

**Comment by Ingrim4** [comment]
That's not us, that's a problem with ProtocolLib not knowing mojang mappings for some packets. Should be fixed by: https://github.com/dmulloy2/ProtocolLib/pull/2940
