### ISSUE TITLE
Orebfuscator blocks view on explode

### ISSUE THREAD

**Issue by vladyaso** [Imprex-Development/orebfuscator#389]
### Description

Hello, how can I make sure that after the explosion of the TNT there are no visual blocks ebfuscator? If anything we have a custom explosion, not vanilla

### Proposed Behaviour

There should be no orebfuscator blocks after the explosion.

### Extra Details

5.4.4

**Comment by Ingrim4** [comment]
To trigger the deobfuscation of blocks, your plugin just needs to call our API. For your reference, here is a [simple example](https://github.com/Imprex-Development/orebfuscator/blob/master/orebfuscator-api-example/src/main/java/net/imprex/api/example/Example.java) of a plugin that adds a pickaxe capable of breaking multiple blocks simultaneously.

**Comment by vladyaso** [comment]
thanks

**Comment by vladyaso** [comment]
@Ingrim4 [19:39:14 ERROR]: Could not pass event EntityExplodeEvent to SpookyItems v1.0.0
java.lang.NullPointerException: Cannot invoke "net.imprex.orebfuscator.api.OrebfuscatorService.deobfuscate(java.util.Collection)" because "this.orebfuscatorService" is null
        at net.katogiri.items.listener.TntListener.onEntityExplode(TntListener.java:222) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(:40) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at co.aikar.timings.TimedEventExecutor.execute(:76) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at org.bukkit.plugin.RegisteredListener.callEvent(:70) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(:624) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.Explosion.a(:291) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.World.createExplosion(:1204) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.WorldServer.createExplosion(:2477) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.World.createExplosion(:1197) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.EntityTNTPrimed.explode(:134) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.EntityTNTPrimed.tick(:93) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(:1566) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(:1161) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(:1565) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(:451) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(:1414) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(:1140) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$1(:289) ~[patched_1.16.5.jar:git-Airplane-"e37fa86"]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Ingrim4** [comment]
The error indicates that `"this.orebfuscatorService" is null`. This might happen if the variable hasn't been initialized or if Orebfuscator isn't installed or running. For instance, this could occur if ProtocolLib isn't running or if it's loaded after your plugin.

To resolve this, ensure that your plugin correctly declares a dependency on Orebfuscator in the `plugin.yml` file. You can refer to an example here: https://github.com/Imprex-Development/orebfuscator/blob/d6ba5bf0537345c306ab4161e1829d9fa835341f/orebfuscator-api-example/src/main/resources/plugin.yml#L10

Additionally, keep in mind that Orebfuscator can only be accessed in the `onEnable` method not `onLoad`. Therefore, you should initialize the `orebfuscatorService` variable in the `onEnable` method rather than in the `onLoad` method. You can see how this is done in the example plugin: https://github.com/Imprex-Development/orebfuscator/blob/d6ba5bf0537345c306ab4161e1829d9fa835341f/orebfuscator-api-example/src/main/java/net/imprex/api/example/Example.java#L28-L36
