### ISSUE TITLE
1.16.3 Support

### ISSUE THREAD

**Issue by schrodingerneko** [Imprex-Development/orebfuscator#43]
**Please fill out the following information:**
* Server Version: 1.16.3
* Orebfuscator Version: last
* Protocollib Version: 4.5.1

**Describe the bug**
Describe the bug clearly and how to produce it

[18:02:35] [Server thread/INFO]: [OFC] Searching NMS protocol for server version "v1_16_R2"!
[18:02:35] [Server thread/ERROR]: [OFC] java.lang.RuntimeException: Server version "v1_16_R2" is currently not supported!
[18:02:35] [Server thread/WARN]: java.lang.RuntimeException: Server version "v1_16_R2" is currently not supported!
[18:02:35] [Server thread/WARN]:        at net.imprex.orebfuscator.NmsInstance.initialize(NmsInstance.java:83)
[18:02:35] [Server thread/WARN]:        at net.imprex.orebfuscator.config.OrebfuscatorConfig.serialize(OrebfuscatorConfig.java:121)
[18:02:35] [Server thread/WARN]:        at net.imprex.orebfuscator.config.OrebfuscatorConfig.reload(OrebfuscatorConfig.java:55)
[18:02:35] [Server thread/WARN]:        at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:48)
[18:02:35] [Server thread/WARN]:        at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:43)
[18:02:35] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:02:35] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[18:02:35] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[18:02:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494)
[18:02:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408)
[18:02:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[18:02:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216)
[18:02:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[18:02:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[18:02:35] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[18:02:35] [Server thread/ERROR]: An error occurred by enabling plugin
[18:02:35] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.0.1
[18:02:35] [Server thread/ERROR]: Error occurred while disabling Orebfuscator v5.0.1 (Is it up to date?)
java.lang.NullPointerException: null
        at net.imprex.orebfuscator.Orebfuscator.onDisable(Orebfuscator.java:75) ~[orebfuscator-plugin-v5.0.0-v16-pre.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.imprex.orebfuscator.Orebfuscator.onEnableFailed(Orebfuscator.java:95) ~[orebfuscator-plugin-v5.0.0-v16-pre.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:358) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by Ingrim4** [comment]
It would seem you didn't download the newest version
