### ISSUE TITLE
NPE on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [Imprex-Development/orebfuscator#48]
**Please fill out the following information:**
* Server Version: 1.16.3
* Orebfuscator Version: 5.0.0-b132
* Protocollib Version: 4.6.0-b480

**Describe the bug**
Shortly after server start-up, the log reported
```
[08:32:35] [chunk-serializer/WARN]: Exception in thread "chunk-serializer" java.lang.NullPointerException
[08:32:35] [chunk-serializer/WARN]:     at net.imprex.orebfuscator.cache.ChunkSerializer.run(ChunkSerializer.java:79)
[08:32:35] [chunk-serializer/WARN]:     at java.base/java.lang.Thread.run(Thread.java:834)
```
No players were connected.

**Comment by Ingrim4** [comment]
Should be fixed with the next commit
